version: '3'

services:
  db:
    container_name: db_pg
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=hypernova
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres: